algorithm: "DQN"
enabled: true
progress_bar: false
skip_learn: false
show_action: false
load: false
load_dir: ""
save: true
state_input_mode: "normalized"
net_arch: [8, 8]
learning_rate: 0.001
gamma: 0.9
exploration_fraction: 0.2
exploration_initial_eps: 1.0
exploration_final_eps: 0.05
buffer_size: 10000
batch_size: 16
target_update_interval: 80
learning_starts: 20
